# Generated by Django 4.1 on 2024-05-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month_of_booking", models.IntegerField()),
                ("day_of_booking", models.IntegerField()),
                ("weekday_of_booking", models.IntegerField()),
                ("month_of_arrival", models.IntegerField()),
                ("day_of_arrival", models.IntegerField()),
                ("weekday_of_arrival", models.IntegerField()),
                ("num_of_nights", models.IntegerField()),
                ("is_repeated_guest", models.BooleanField()),
                ("previous_stays", models.IntegerField()),
                ("previous_cancellations", models.IntegerField()),
                ("booking_to_arrival_duration", models.IntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("override", models.DecimalField(decimal_places=2, max_digits=10)),
                ("probability", models.DecimalField(decimal_places=6, max_digits=10)),
                ("prediction", models.BooleanField()),
                ("guest_name", models.CharField(max_length=255)),
                ("date_booking_made", models.DateField()),
                ("scheduled_arrival", models.DateField()),
            ],
        ),
    ]
