# Generated by Django 4.2.13 on 2024-05-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cancellationPredictor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="guest_name",
            field=models.TextField(),
        ),
    ]
